/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TierRouteImport } from './routes/$tier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTierIdRouteImport } from './routes/t.$tier.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TierRoute = TierRouteImport.update({
  id: '/$tier',
  path: '/$tier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTierIdRoute = TTierIdRouteImport.update({
  id: '/t/$tier/$id',
  path: '/t/$tier/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tier': typeof TierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/t/$tier/$id': typeof TTierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tier': typeof TierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/t/$tier/$id': typeof TTierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tier': typeof TierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/t/$tier/$id': typeof TTierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$tier' | '/sitemap.xml' | '/t/$tier/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$tier' | '/sitemap.xml' | '/t/$tier/$id'
  id: '__root__' | '/' | '/$tier' | '/sitemap.xml' | '/t/$tier/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TierRoute: typeof TierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TTierIdRoute: typeof TTierIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tier': {
      id: '/$tier'
      path: '/$tier'
      fullPath: '/$tier'
      preLoaderRoute: typeof TierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tier/$id': {
      id: '/t/$tier/$id'
      path: '/t/$tier/$id'
      fullPath: '/t/$tier/$id'
      preLoaderRoute: typeof TTierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TierRoute: TierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TTierIdRoute: TTierIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
